config/routes.rb
Rails.application.routes.draw do

  
  resources :papers, except: [:show]
  get '/papers/:id/veja' => 'papers#show', as: :paper_show 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  # Way to configure Root path for some controller generated by devise

  #PDF View
  mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'
  
  
  
  
  #get '/pdf_render' => 'application#pdf_render', as: :pdf_render


  authenticated :coordinator do
    root 'coordinators#index', as: :authenticated_coordinator_root
    get 'coordinator/pending' => 'coordinators#coordinator_pendings_papers', as: :coordinator_pendings
    get 'coordinator/onhold' => 'coordinators#coordinator_onhold_papers', as: :coordinator_onhold
    get 'coordinator/concluded' => 'coordinators#coordinator_concluded_papers', as: :coordinator_concluded
    get 'coordinator/index' => 'coordinators#index', as: :coordinator_index
    get 'coordinator/take_paper' => 'coordinators#take_paper', as: :take_paper
    get 'coordinator/return_paper' => 'coordinators#return_paper', as: :return_paper
    patch 'coordinator/allocate' => 'coordinators#allocate_reviewer', as: 'allocate_reviewer'
    get 'coordinator/desallocate' => 'coordinators#desallocate_reviewer', as: 'desallocate_reviewer'
    patch 'coordinator/concluded' => 'coordinators#concluded?', as: :concluded
    get 'coordinator/:paper_id/veja-mais' => 'coordinators#show_paper', as: :coordinator_show_paper
    get 'historico' => 'coordinators#coordinator_events', as: :coordinator_events

     # PDF VIEW
    get 'coordinator/:paper_id/pdf_render' => 'application#pdf_render'
  end
  authenticated :professor do
    get '/papers/:id/pdf_render' => 'application#pdf_render'
    root 'professors#index', as: :authenticated_professor_root
    get 'professor/pending' => 'professors#professor_pending_papers', as: :professor_pending
    get 'professor/concluded' => 'professors#professor_concluded_papers', as: :professor_concluded
    get 'professor/:paper_id/historico' => 'professors#events', as: :events
    get 'professor/index' => 'professors#index', as: :professor_index
  end
  authenticated :reviewer do
    root 'reviewers#index', as: :authenticated_reviewer_root
    get 'reviewer/pending' => 'reviewers#reviewer_pending_papers', as: :reviewer_pending
    get 'reviewer/concluded' => 'reviewers#reviewer_concluded_papers', as: :reviewer_concluded
    get 'reviewer/index' => 'reviewers#index', as: :reviewer_index
    get 'reviewer/:paper_id/edit' => 'reviewers#reviewer_edit', as: :reviewer_edit
    patch 'reviewer/edit/save' => 'reviewers#reviewer_save', as: :reviewer_save

    #PDF VIEW
    get 'reviewer/:paper_id/pdf_render' => 'application#pdf_render' 
  end
  

  
  devise_for :professors, controllers: {
    sessions: 'professors/sessions',
    passwords: 'professors/passwords'
  }
  devise_for :coordinators, controllers: {
    sessions: 'coordinators/sessions',
    passwords: 'coordinators/passwords'
  }
  devise_for :reviewers, controllers: {
    sessions: 'reviewers/sessions',
    passwords: 'reviewers/passwords'
  }

  # Login
  get 'login' => "logins#login", as: :logins
  get 'update_login_form' => "logins#update_login_form", as: :update_login_form

  # Root definition: in the end of file
  root 'logins#login'

  

end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  layout 'login'
  def login
  end

  def update_login_form
    if params[:login_type] == "COORDENADOR"
      render '_form_coordinator', :layout => false
    elsif params[:login_type] == "REVISOR"
      render '_form_reviewer', :layout => false
    elsif params[:login_type] == "PROFESSOR"
      render '_form_professor', :layout => false
    end
  end
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/views/logins/_form_coordinator.html.erb
<%= form_for(Coordinator.new, url: coordinator_session_path,class:'form-signin', :id => "fmLogin" ) do |f| %>

    <%= f.label :email, class:"control-label sr-only" %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email", class:"form-control", id:"email", placeholder: 'Email de coordenador' %>

    <%= f.label :password, class:"control-label sr-only" %><br />
    <%= f.password_field :password, autocomplete: "off", class:"form-control", id:"password", placeholder: 'Senha de coordenador' %>

    <%= link_to 'Recuperar senha', new_coordinator_password_path %>

  <div class="actions">
    <%= f.submit "Entrar", id:"btn-logar", class:"btn btn-primary btn-lg btn-block" %>
  </div>
<% end %>

app/views/logins/_form_professor.html.erb
<%= form_for(Professor.new, url: professor_session_path,class:'form-signin', :id => "fmLogin" ) do |f| %>

    <%= f.label :email, class:"control-label sr-only" %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email", class:"form-control", id:"email", placeholder: 'Email de professor' %>

    <%= f.label :password, class:"control-label sr-only" %><br />
    <%= f.password_field :password, autocomplete: "off", class:"form-control", id:"password", placeholder: 'Senha de professor' %>

    <%= link_to 'Recuperar senha', new_professor_password_path %>

  <div class="actions">
    <%= f.submit "Entrar", id:"btn-logar", class:"btn btn-primary btn-lg btn-block" %>
  </div>
<% end %>

app/views/logins/_form_reviewer.html.erb
<%= form_for(Reviewer.new, url: reviewer_session_path,class:'form-signin', :id => "fmLogin" ) do |f| %>

    <%= f.label :email, class:"control-label sr-only" %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email", class:"form-control", id:"email", placeholder: 'Email de revisor' %>

    <%= f.label :password, class:"control-label sr-only" %><br />
    <%= f.password_field :password, autocomplete: "off", class:"form-control", id:"password", placeholder: 'Senha de revisor' %>

    <%= link_to 'Recuperar senha', new_reviewer_password_path %>

  <div class="actions">
    <%= f.submit "Entrar", id:"btn-logar", class:"btn btn-primary btn-lg btn-block" %>
  </div>
<% end %>

app/views/logins/login.html.erb
<div class="wrapper-login">
  <div class="form-group">
    <p class="text-center">
      <select id="login-type-select" class="form-control">
        <option value="COORDENADOR" selected="true">Coordenador</option>
        <option value="REVISOR">Revisor</option>
        <option value="PROFESSOR">Professor</option>
      </select>
    </p>
  <div id="login-content"></div>
</div>