config/routes.rb
Rails.application.routes.draw do

  
  resources :papers, except: [:show]
  get '/papers/:id/veja' => 'papers#show', as: :paper_show 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  # Way to configure Root path for some controller generated by devise

  #PDF View
  mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'
  
  
  
  
  #get '/pdf_render' => 'application#pdf_render', as: :pdf_render


  authenticated :coordinator do
    root 'coordinators#index', as: :authenticated_coordinator_root
    get 'coordinator/pending' => 'coordinators#coordinator_pendings_papers', as: :coordinator_pendings
    get 'coordinator/onhold' => 'coordinators#coordinator_onhold_papers', as: :coordinator_onhold
    get 'coordinator/concluded' => 'coordinators#coordinator_concluded_papers', as: :coordinator_concluded
    get 'coordinator/index' => 'coordinators#index', as: :coordinator_index
    get 'coordinator/take_paper' => 'coordinators#take_paper', as: :take_paper
    get 'coordinator/return_paper' => 'coordinators#return_paper', as: :return_paper
    patch 'coordinator/allocate' => 'coordinators#allocate_reviewer', as: 'allocate_reviewer'
    get 'coordinator/desallocate' => 'coordinators#desallocate_reviewer', as: 'desallocate_reviewer'
    patch 'coordinator/concluded' => 'coordinators#concluded?', as: :concluded
    get 'coordinator/:paper_id/veja-mais' => 'coordinators#show_paper', as: :coordinator_show_paper
    get 'historico' => 'coordinators#coordinator_events', as: :coordinator_events

     # PDF VIEW
    get 'coordinator/:paper_id/pdf_render' => 'application#pdf_render'
  end
  authenticated :professor do
    get '/papers/:id/pdf_render' => 'application#pdf_render'
    root 'professors#index', as: :authenticated_professor_root
    get 'professor/pending' => 'professors#professor_pending_papers', as: :professor_pending
    get 'professor/concluded' => 'professors#professor_concluded_papers', as: :professor_concluded
    get 'professor/:paper_id/historico' => 'professors#events', as: :events
    get 'professor/index' => 'professors#index', as: :professor_index
  end
  authenticated :reviewer do
    root 'reviewers#index', as: :authenticated_reviewer_root
    get 'reviewer/pending' => 'reviewers#reviewer_pending_papers', as: :reviewer_pending
    get 'reviewer/concluded' => 'reviewers#reviewer_concluded_papers', as: :reviewer_concluded
    get 'reviewer/index' => 'reviewers#index', as: :reviewer_index
    get 'reviewer/:paper_id/edit' => 'reviewers#reviewer_edit', as: :reviewer_edit
    patch 'reviewer/edit/save' => 'reviewers#reviewer_save', as: :reviewer_save

    #PDF VIEW
    get 'reviewer/:paper_id/pdf_render' => 'application#pdf_render' 
  end
  

  
  devise_for :professors, controllers: {
    sessions: 'professors/sessions',
    passwords: 'professors/passwords'
  }
  devise_for :coordinators, controllers: {
    sessions: 'coordinators/sessions',
    passwords: 'coordinators/passwords'
  }
  devise_for :reviewers, controllers: {
    sessions: 'reviewers/sessions',
    passwords: 'reviewers/passwords'
  }

  # Login
  get 'login' => "logins#login", as: :logins
  get 'update_login_form' => "logins#update_login_form", as: :update_login_form

  # Root definition: in the end of file
  root 'logins#login'

  

end

app/models/coordinator.rb
class Coordinator < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

  has_many :papers, foreign_key: 'coordinator_id',
                    primary_key: 'id'
end

app/controllers/coordinators/confirmations_controller.rb
# frozen_string_literal: true

class Coordinators::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/coordinators/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Coordinators::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/coordinators/passwords_controller.rb
# frozen_string_literal: true

class Coordinators::PasswordsController < Devise::PasswordsController
  layout 'login'
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/coordinators/registrations_controller.rb
# frozen_string_literal: true

class Coordinators::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/coordinators/sessions_controller.rb
# frozen_string_literal: true

class Coordinators::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    redirect_to logins_path
  end

  # POST /resource/sign_in
  def create
        self.resource = warden.authenticate!(auth_options)
    set_flash_message!(:notice, :signed_in)
    sign_in(resource_name, resource)
    yield resource if block_given?
    redirect_to coordinator_index_path  
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/coordinators/unlocks_controller.rb
# frozen_string_literal: true

class Coordinators::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/coordinators_controller.rb
class CoordinatorsController < ApplicationController
  before_action :authenticate_coordinator!
  before_action :find_paper, only: [:show_paper, :take_paper, :return_paper, :allocate_reviewer, :desallocate_reviewer, :concluded?, :pdf_render, :coordinator_events]
  layout 'coordinator'
  def index
    @all_papers = Paper.select{|paper| paper.coordinator_id == nil}
    # @coordinator_papers = Paper.all.where(coordinator_id: current_coordinator.id).order('updated_at DESC')
    @coordinator_papers_concluded = Paper.all.select{ |paper| paper.coordinator_id==current_coordinator.id && paper.status=='CONCLUIDA'}.size
    @coordinator_papers = Paper.all.select{ |paper| paper.coordinator_id==current_coordinator.id && paper.status!='CONCLUIDA'}.size
    @coordinator_papers_pending = Paper.select{|paper| paper.coordinator_id == current_coordinator.id && (paper.status == 'RECEBIDO' || paper.status == 'DEVOLVIDO')}.size
  end

  def coordinator_pendings_papers
    @coordinator_papers_pending = Paper.select{|paper| paper.coordinator_id == current_coordinator.id && (paper.status == 'RECEBIDO' || paper.status == 'DEVOLVIDO')}
  end
  
  def coordinator_onhold_papers
    @coordinator_papers = Paper.all.select{ |paper| paper.coordinator_id==current_coordinator.id && paper.status!='CONCLUIDA'}
  end
  
  def coordinator_concluded_papers
    @coordinator_papers_concluded = Paper.all.select{ |paper| paper.coordinator_id==current_coordinator.id && paper.status=='CONCLUIDA'}
  end

  def show_paper
    @reviewers = Reviewer.all
  end

  def coordinator_events
    @events = @paper.events 
  end

  def take_paper
    if @paper.update(coordinator_id: current_coordinator.id, status: 'RECEBIDO')
      Event.create(log: 'Recebido pelo coordenador', paper_id: @paper.id)
      redirect_to coordinator_index_path, notice: 'Artigo capturado com sucesso'
    else
      redirect_to coordinator_index_path, notice: 'Não foi possível capturar este artigo, ele escapou das suas mãos.'
    end
  end
  def return_paper
    if @paper.update(coordinator_id: nil, reviewer_id: nil, status:'SUBMETIDO')
      Event.create(log: 'Artigo devolvido pelo coordenador', paper_id: @paper.id)
      redirect_to coordinator_index_path, notice: 'Artigo devolvido para selva com sucesso'
    else
      redirect_to coordinator_index_path, notice: 'Não foi possível devolver este artigo, ele se apegou a você.'
    end
  end

  def allocate_reviewer
    if @paper.update(reviewer_id: params[:paper][:reviewer_id], status: 'REVISOR')
      Event.create(log: 'Enviado para revisor', paper_id: @paper.id)
      redirect_to coordinator_index_path, notice: 'Artigo alocado com sucesso.'
    else
      redirect_to coordinator_index_path, notice: 'Não foi possível alocar este artigo.'
    end
  end

  def desallocate_reviewer
    if @paper.update(reviewer_id: nil, status: 'RECEBIDO')
      Event.create(log: 'Recebido pelo coordenador. Coordenador removeu o revisor para o artigo' ,paper_id: @paper.id)
      redirect_to coordinator_index_path, notice: 'Revisor desalocado com sucesso.'
    else
      redirect_to coordinator_index_path, notice: 'Não foi possível desalocar este revisor.'
    end
  end

  def concluded?
    if @paper.update(status: params[:paper][:status])
      if params[:paper][:status] == 'CONCLUIDA'
        Event.create(log: 'Revisão foi aprovada. Procedimento concluído', paper_id: @paper.id)
      else
        Event.create(log: 'Revisão não foi aprovada pelo coordenador. Artigo voltou para o revisor.', paper_id: @paper.id)
      end
      redirect_to coordinator_index_path, notice: 'Artigo atualizado com sucesso.'
    else
      redirect_to coordinator_index_path, notice: 'Não foi possível atualizar este artigo.'
    end

  end
  def pdf_render
    if params[:type_of_file] == 'original'
      @modal_header = 'Artigo Original' 
      @file = @paper.original_file_key.file.file.split('/').last
    else
      @modal_header = 'Artigo Revisado'
      @file = @paper.reviewed_file_key.file.file.split('/').last
    end
    render '_pdf_render', :layout => false
  end

  private 

  def find_paper
    @paper = Paper.find(params[:paper_id])
  end
end

app/helpers/coordinators_helper.rb
module CoordinatorsHelper
end

app/views/coordinators/coordinator_concluded_papers.html.erb
<script type="text/javascript">
  $(function(){
    document.addEventListener("turbolinks:before-cache", function() {
      dataTable.destroy();
    });
    var dataTable = $("#my-papers-concluded-table").DataTable();
  })
</script>

<div class="col-md-3">
  <p><%= link_to "Voltar", root_path, class: 'btn btn-info'%></p>
</div>

<div class="col-md-12">
  <div class="panel panel-default">
    <div class="panel-body">
      <p><b>PENDÊNCIAS</b></p>
      <div class="my-papers">
        <table id="my-papers-concluded-table" class="display-dataTables">
          <thead>
            <tr>
              <th>título</th>
              <th>Professor</th>
              <th>Estado</th>
              <th>Atualizado em:</th>        
              <th>Edição</th>
            </tr>
          </thead>

          <tbody>
            <% if !@coordinator_papers_concluded.empty? %>
            <% @coordinator_papers_concluded.each do |paper|%>
            <tr>
              <td><%= paper.title %></td>
              <td><%= paper.professor.name %></td>
              <td><%= paper_status(paper.status) %></td>
              <td><%= paper.updated_at%></td>
              <td><%= link_to "Ver Mais", coordinator_show_paper_path(paper_id: paper.id), class: 'btn btn-info' %></td>
            </tr>
            <% end %>
            <% else%>
            <td><b>Nenhuma revisão foi concluída.</b></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/coordinators/coordinator_events.html.erb
<script type="text/javascript">
  $(function(){
    document.addEventListener("turbolinks:before-cache", function() {
      dataTable.destroy();
    });
    var dataTable = $("#events-table").DataTable({
      "ordering": false,
      "searching": false,
      "lengthChange": false,
      "paging": false
    });
  })
</script>
<% puts "aaaaa"%>
<%= puts @paper.status%>
<div class="row">
  <p><%= link_to 'Voltar', coordinator_show_paper_path(paper_id: @paper.id), class: 'btn btn-info'%></p>
</div>

<div class="panel panel-default">
  <div class="panel-body">
    <h3 class="centralizar"><b>HISTÓRICO</b></h3>
    <table id="events-table">
      <thead>
        <tr>
          <th>Data</th>
          <th>Movimentação</th>
        </tr>
      </thead>
      <tbody>
        <% @events.each do |event|%>
        <tr>
          <td>[<%= event.created_at%>]</td>
          <td><b><%= event.log %></b></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/coordinators/coordinator_onhold_papers.html.erb
<script type="text/javascript">
  $(function(){
    document.addEventListener("turbolinks:before-cache", function() {
      dataTable.destroy();
    });
    var dataTable = $("#my-papers-table").DataTable();
  })
</script>
<div class="col-md-3">
  <p><%= link_to "Voltar", root_path, class: 'btn btn-info'%></p>
</div>

<div class="col-md-12">

  <div class="panel panel-default">
    <div class="panel-body">
      <p><b>SEUS ARTIGOS</b></p>
      <div class="my-papers">
        <table id="my-papers-table" class="display-dataTables">
          <thead>
            <tr>
              <th>título</th>
              <th>Professor</th>
              <th>Estado</th>
              <th>Atualizado em:</th>        
              <th>Edição</th>
            </tr>
          </thead>

          <tbody>
            <% @coordinator_papers.each do |paper|%>
            <tr>
              <td><%= paper.title %></td>
              <td><%= paper.professor.name %></td>
              <td><%= paper_status(paper.status) %></td>
              <td><%= paper.updated_at%></td>
              <td><%= link_to "Ver Mais", coordinator_show_paper_path(paper_id: paper.id), class: 'btn btn-info' %> &nbsp&nbsp 
                  <%= link_to return_paper_path(:paper_id => paper.id), data: { confirm: 'Tem certeza que quer devolver este artigo?' }, title: 'Desvincular-se do artigo.', class: 'return-paper-hover' do %>  
                    <i class="fas fa-window-close"></i>
                  <% end %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/coordinators/coordinator_pendings_papers.html.erb
<script type="text/javascript">
  $(function(){
    document.addEventListener("turbolinks:before-cache", function() {
      dataTable.destroy();
    });
    var dataTable = $("#my-papers-pending-table").DataTable();
  })
</script>

<div class="col-md-3">
  <p><%= link_to "Voltar", root_path, class: 'btn btn-info'%></p>
</div>

<div class="col-md-12">

  <div class="panel panel-default">
    <div class="panel-body">
      <p><b>PENDÊNCIAS</b></p>
      <div class="my-papers">
        <table id="my-papers-pending-table" class="display-dataTables">
          <thead>
            <tr>
              <th>título</th>
              <th>Professor</th>
              <th>Estado</th>
              <th>Atualizado em:</th>        
              <th>Edição</th>
            </tr>
          </thead>

          <tbody>
            <% if !@coordinator_papers_pending.empty? %>
            <% @coordinator_papers_pending.each do |paper|%>
            <tr>
              <td><%= paper.title %></td>
              <td><%= paper.professor.name %></td>
              <td><%= paper_status(paper.status) %></td>
              <td><%= paper.updated_at%></td>
              <td><%= link_to "Ver Mais", coordinator_show_paper_path(paper_id: paper.id), class: 'btn btn-info' %> &nbsp&nbsp 
                  <%= link_to return_paper_path(:paper_id => paper.id), data: { confirm: 'Tem certeza que quer devolver este artigo?' }, title: 'Desvincular-se do artigo.', class: 'return-paper-hover' do %>  
                    <i class="fas fa-window-close"></i>
                  <% end %>
              </td>
            </tr>
            <% end %>
            <% else%>
            <td><b>Não existe pendência</b></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
    
  </div>
</div>

app/views/coordinators/index.html.erb
<script type="text/javascript">
  $(function(){
    document.addEventListener("turbolinks:before-cache", function() {
      dataTable.destroy();
    });
    var dataTable = $("#not-my-papers-table").DataTable();
  })
</script>

<div  class="col-md-4 text-center">
  <div class="panel panel-default">
    <div class="panel-body">
      <p><i class="fas fa-calendar-times"></i>
        <%= @coordinator_papers_pending %>
      Pendências</p>
    </div>
    <div class="panel-footer">
      <%= link_to coordinator_pendings_path, class: 'btn btn-default' do %>
      Suas Pendências <i class="fas fa-arrow-circle-right"></i> 
      <% end %>
    </div>
  </div>
</div>
<div  class="col-md-4 text-center">
  <div class="panel panel-default">
    <div class="panel-body">
      <p><i class="fas fa-calendar-minus"></i>
        <%= @coordinator_papers %>
      Artigos para serem revisados</p>
    </div>
    <div class="panel-footer">
      <%= link_to coordinator_onhold_path, class: 'btn btn-default' do %>
      Ver Artigos <i class="fas fa-arrow-circle-right"></i> 
      <% end %>
    </div>
  </div>
</div>
<div  class="col-md-4 text-center">
  <div class="panel panel-default">
    <div class="panel-body">
      <p><i class="fas fa-calendar-check"></i>
        <%= @coordinator_papers_concluded %>
      Revisões Concluídas</p>
    </div>
    <div class="panel-footer">
      <%= link_to coordinator_concluded_path, class: 'btn btn-default' do %>
      Ver Mais <i class="fas fa-arrow-circle-right"></i> 
      <% end %>
    </div>
  </div>
</div>

<div class="col-md-12">
  <div class="panel panel-default">
    <div class="panel-body">
      <p><b>TODOS OS ARTIGOS</b></p>
      <table id="not-my-papers-table">
        <thead>
          <tr>
            <th>título</th>
            <th>Professor</th>
            <th>Estado</th>
            <th>Data de submissão</th>
            <th>Informações</th>
            <th>Alocar-se</th>
          </tr>
        </thead>
        <tbody>
          <% if !@all_papers.empty?%>
          <% @all_papers.each do |paper|%>
          <tr>
            <td><%= paper.title %></td>
            <td><%= paper.professor.name %></td>
            <td><%= paper_status(paper.status) %></td>
            <td><%= paper.created_at.to_date%></td>
            <td><%= link_to 'Ver Mais', coordinator_show_paper_path(paper_id: paper.id)%></td>
            <td><%= link_to 'Apropriar-se', take_paper_path(:paper_id => paper.id)%></td>
          </tr>
          <% end %>
          <% else %>
          <tr>
            <td><b>Não existe artigo submetido</b></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/coordinators/show_paper.html.erb
<%= javascript_include_tag 'pdf-modal'%>
<div id="pdf-view" class="col-md-8"></div>

<div class="row">
  <div class="col-md-2">
  </div>
  <div class="col-md-4">
    <%if @paper.status=='RECEBIDO' || @paper.status=='DEVOLVIDO'%>
      <p><%= link_to "Voltar", coordinator_pendings_path, class: 'btn btn-info'%></p>
    <% elsif @paper.status=='CONCLUIDA'%>
      <p><%= link_to "Voltar", coordinator_concluded_path, class: 'btn btn-info'%></p>
    <% elsif @paper_status!='CONCLUIDA'%>
      <p><%= link_to "Voltar", coordinator_onhold_path, class: 'btn btn-info'%></p>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="col-md-2">
  </div>
  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <p class="text-center"><%= @paper.title.upcase%></p>
      </div>
      <div class="panel-body">
        <!-- LINHA COM O NOME DO PROFESSOR -->
        <div class="row">
          <div class="col-md-4">
            <p class="text-left"><b>Professor:</b></p>
          </div>
          <div class="col-md-8">
            <p class="text-left"><%= @paper.professor.name%></p>
          </div>
        </div>
        <!-- LINHA COM O ESTADO DO ARTIGO -->
        <div class="row">
          <div class="col-md-4">
            <p class="text-left"><b>Estado:</b></p>
          </div>
          <div class="col-md-8">
            <p class="text-left"><%= paper_status(@paper.status)%></p>
          </div>
        </div>
        <!-- LINHA COM O REVISOR -->
        <% if @paper.coordinator_id != nil%>
        <div class="row">
          <div class="col-md-4">
            <p class="text-left"><b>Revisor:</b></p>
          </div>
          <div class="col-md-8">
            <% if @paper.reviewer_id!=nil%>
            <p class="text-left"><%= @paper.reviewer.name %> 
              <% if @paper.status!='CONCLUIDA'%>
                <%= link_to 'Remover Revisor', desallocate_reviewer_path(:paper_id => @paper.id), data: { confirm: 'Tem certeza que deseja remover o revisor deste artigo?'}, class: 'btn btn-danger btn-sm' %></p>
              <% end %>
            <% else %>
            <%= form_for @paper, :url => allocate_reviewer_path(:paper_id => @paper.id) do |f|%>
            <p class="text-left">
              <%=  f.select :reviewer_id, options_for_select(@reviewers.collect{|reviewer| [reviewer.name, reviewer.id]}), {}, {:class => "form-control select-size"} %> <%= f.submit 'Atribuir', class: 'btn btn-primary'%></p>
            </p>
            <% end %>
            <% end %>
          </div>
        </div>
        <% end %>
        <!-- LINHA COM O ARTIGO ORIGINAL -->
        <div class="row">
          <div class="col-md-4">
            <p class="text-left"><b>Artigo Submetido:</b></p>
          </div>
          <div class="col-md-8">
            <p class="text-left">
              <%= link_to @paper.original_file_key.url, class: 'btn btn-primary', target: :_blank do %>
              <i class="fas fa-download"></i>
              Baixar
              <% end %>
            </p>
          </div>
        </div>
        <!-- LINHA COM O ARTIGO REVISADO -->
        <% if @paper.status=='DEVOLVIDO' || @paper.status=='VOLTOU REVISOR' || @paper.status=='CONCLUIDA'%>
        <div class="row">
          <div class="col-md-4">
            <p class="text-left"><b>Artigo Revisado:</b></p>
          </div>
          <div class="col-md-8">
            <p class="text-left">
              <%= link_to @paper.reviewed_file_key.url, target: :_blank, class: 'btn btn-primary' do %>
              <i class="fas fa-download"></i>
              Baixar
              <% end %>
            </p>
          </div>
        </div>
        <% end %>
        <!-- LINHA COM O ARTIGO DEVOLVIDO-->
        <% if @paper.status == 'DEVOLVIDO'%>
        <div class="row">
          <div class="col-md-4">
            <p class="text-left"><b>Revisão:</b></p>
          </div>
          <div class="col-md-8">
            <%= form_for @paper, :url  => concluded_path(:paper_id => @paper.id) do |f|%>
            <p class="text-left"><%= f.select :status, options_for_select([['Aprovada', 'CONCLUIDA'], ['Desaprovada', 'VOLTOU REVISOR']]), {}, {class: 'form-control select-size'}%> <%= f.submit 'Enviar', class: 'btn btn-primary' %></p>
            <% end %>
          </div>
        </div>
        <% end %>

        <div class="row">
          <div class="col-md-4">
            <p class="text-left"><b>Submetido em: </b></p>
          </div>
          <div class="col-md-8">
            <p class="text-left"><%= @paper.created_at.strftime("%d/%m/%Y - %H:%M") %></p>
          </div>
        </div>

        <% if @paper.status == 'CONCLUIDA' %>
          <div class="row">
            <div class="col-md-4">
              <p class="text-left"><b>Concluido em: </b></p>
            </div>
            <div class="col-md-8">
              <p class="text-left"><%= @paper.updated_at.strftime("%d/%m/%Y - %H:%M") %></p>
            </div>
          </div>
        <% end %>

        <div class="row">
          <div class="col-md-4">
            <p><b>Histórico: </b></p>
          </div>
          <div class="col-md-8">
            <p><%= link_to 'Ver Histórico', coordinator_events_path(paper_id: @paper.id), class: 'btn btn-primary'%></p>
          </div>
        </div>
        <!-- LINHA PARA DEVOLVER O ARTIGO -->
          <%if @paper.coordinator_id!=nil%>
            <% if @paper.status!='CONCLUIDA'%>
              <div class="row">
                <p class="text-center"><%= link_to 'Desvincular-se do artigo', return_paper_path(:paper_id => @paper.id), data: { confirm: 'Tem certeza que quer devolver este artigo?' }, class: 'btn btn-danger '%></p>
              </div>
            <% end %>
          <% else %>
            <div class="row">
              <p class="text-center"><%= link_to 'Apropriar-se', take_paper_path(:paper_id => @paper.id), class: 'btn btn-primary'%></p>
            </div>
          <% end %>
        </div>

      </div>
  <div class="col-md-2">
  </div>
</div>