config/routes.rb
Rails.application.routes.draw do

  
  resources :papers, except: [:show]
  get '/papers/:id/veja' => 'papers#show', as: :paper_show 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  # Way to configure Root path for some controller generated by devise

  #PDF View
  mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'
  
  
  
  
  #get '/pdf_render' => 'application#pdf_render', as: :pdf_render


  authenticated :coordinator do
    root 'coordinators#index', as: :authenticated_coordinator_root
    get 'coordinator/pending' => 'coordinators#coordinator_pendings_papers', as: :coordinator_pendings
    get 'coordinator/onhold' => 'coordinators#coordinator_onhold_papers', as: :coordinator_onhold
    get 'coordinator/concluded' => 'coordinators#coordinator_concluded_papers', as: :coordinator_concluded
    get 'coordinator/index' => 'coordinators#index', as: :coordinator_index
    get 'coordinator/take_paper' => 'coordinators#take_paper', as: :take_paper
    get 'coordinator/return_paper' => 'coordinators#return_paper', as: :return_paper
    patch 'coordinator/allocate' => 'coordinators#allocate_reviewer', as: 'allocate_reviewer'
    get 'coordinator/desallocate' => 'coordinators#desallocate_reviewer', as: 'desallocate_reviewer'
    patch 'coordinator/concluded' => 'coordinators#concluded?', as: :concluded
    get 'coordinator/:paper_id/veja-mais' => 'coordinators#show_paper', as: :coordinator_show_paper
    get 'historico' => 'coordinators#coordinator_events', as: :coordinator_events

     # PDF VIEW
    get 'coordinator/:paper_id/pdf_render' => 'application#pdf_render'
  end
  authenticated :professor do
    get '/papers/:id/pdf_render' => 'application#pdf_render'
    root 'professors#index', as: :authenticated_professor_root
    get 'professor/pending' => 'professors#professor_pending_papers', as: :professor_pending
    get 'professor/concluded' => 'professors#professor_concluded_papers', as: :professor_concluded
    get 'professor/:paper_id/historico' => 'professors#events', as: :events
    get 'professor/index' => 'professors#index', as: :professor_index
  end
  authenticated :reviewer do
    root 'reviewers#index', as: :authenticated_reviewer_root
    get 'reviewer/pending' => 'reviewers#reviewer_pending_papers', as: :reviewer_pending
    get 'reviewer/concluded' => 'reviewers#reviewer_concluded_papers', as: :reviewer_concluded
    get 'reviewer/index' => 'reviewers#index', as: :reviewer_index
    get 'reviewer/:paper_id/edit' => 'reviewers#reviewer_edit', as: :reviewer_edit
    patch 'reviewer/edit/save' => 'reviewers#reviewer_save', as: :reviewer_save

    #PDF VIEW
    get 'reviewer/:paper_id/pdf_render' => 'application#pdf_render' 
  end
  

  
  devise_for :professors, controllers: {
    sessions: 'professors/sessions',
    passwords: 'professors/passwords'
  }
  devise_for :coordinators, controllers: {
    sessions: 'coordinators/sessions',
    passwords: 'coordinators/passwords'
  }
  devise_for :reviewers, controllers: {
    sessions: 'reviewers/sessions',
    passwords: 'reviewers/passwords'
  }

  # Login
  get 'login' => "logins#login", as: :logins
  get 'update_login_form' => "logins#update_login_form", as: :update_login_form

  # Root definition: in the end of file
  root 'logins#login'

  

end

app/models/professor.rb
class Professor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
  
  has_many :papers, :foreign_key => 'professor_id',
                    :primary_key => 'id'
end

app/controllers/professors/confirmations_controller.rb
# frozen_string_literal: true

class Professors::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/professors/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Professors::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/professors/passwords_controller.rb
# frozen_string_literal: true

class Professors::PasswordsController < Devise::PasswordsController
  layout 'login'
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/professors/registrations_controller.rb
# frozen_string_literal: true

class Professors::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/professors/sessions_controller.rb
# frozen_string_literal: true

class Professors::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    redirect_to logins_path
  end

  # POST /resource/sign_in
  def create
    self.resource = warden.authenticate!(auth_options)
    set_flash_message!(:notice, :signed_in)
    sign_in(resource_name, resource)
    yield resource if block_given?
    redirect_to professor_index_path
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/professors/unlocks_controller.rb
# frozen_string_literal: true

class Professors::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/professors_controller.rb
class ProfessorsController < ApplicationController
  before_action :authenticate_professor!
  before_action :find_paper, only: [:events]
  layout 'professor'

  def index
    # @professor_papers_concluded = Paper.select{|paper|  paper.professor_id == current_professor.id && paper.status == 'CONCLUIDA'}
    # @professor_papers_pending = Paper.select{|paper|  paper.professor_id == current_professor.id && paper.status != 'CONCLUIDA'}
    @professor_papers_concluded = Paper.select{|paper|  paper.professor_id == current_professor.id && paper.status == 'CONCLUIDA'}.size
    @professor_papers_pending = Paper.select{|paper|  paper.professor_id == current_professor.id && paper.status != 'CONCLUIDA'}.size
    @professor_papers = Paper.select{|paper| paper.coordinator_id == nil}
  end
  def professor_pending_papers
    @professor_papers_pending = Paper.select{|paper|  paper.professor_id == current_professor.id && paper.status != 'CONCLUIDA'}
  end
  def professor_concluded_papers
    @professor_papers_concluded = Paper.select{|paper|  paper.professor_id == current_professor.id && paper.status == 'CONCLUIDA'}
  end


  def events
    @events = @paper.events 
  end
 
  private

  def find_paper
    @paper = Paper.find(params[:paper_id])
  end
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/views/professors/events.html.erb
<script type="text/javascript">
  $(function(){
    document.addEventListener("turbolinks:before-cache", function() {
      dataTable.destroy();
    });
    var dataTable = $("#events-table").DataTable({
      "ordering": false,
      "searching": false,
      "lengthChange": false,
      "paging": false
    });
  })
</script>

<div class="row">
  <% if @paper.status == "CONCLUIDA"%>
    <p><%= link_to "Voltar", professor_concluded_path, class: 'btn btn-info'%></p>
  <%elsif @paper.status == "SUBMETIDO"%>
    <p><%= link_to "Voltar", root_path, class: 'btn btn-info'%></p>
  <% else %>
    <p><%= link_to "Voltar", professor_pending_path, class: 'btn btn-info'%></p>
  <% end %> 
</div>

<div class="panel panel-default">
  <div class="panel-body">
    <h3 class="centralizar"><b>HISTÓRICO</b></h3>
    <table id="events-table">
      <thead>
        <tr>
          <th>Data</th>
          <th>Movimentação</th>
        </tr>
      </thead>
      <tbody>
        <% @events.each do |event|%>
        <tr>
          <td>[<%= event.created_at%>]</td>
          <td><b><%= event.log %></b></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/professors/index.html.erb
<script type="text/javascript">
  $(function(){
    document.addEventListener("turbolinks:before-cache", function() {
      dataTable.destroy();
    });
    var dataTable = $("#professor-paper-without-coordinator-table").DataTable();
  })
</script>
<div class="col-md-4 text-center">
  <div class="panel painel-default">
    <div class="panel-body">
      <p><i class="fas fa-calendar-minus"></i> 
      <%= @professor_papers_pending %>
      Artigos esperando revisão</p>
    </div>
    <div class="panel-footer">
      <%= link_to professor_pending_path, class: 'btn btn-default' do %>
        Ver Mais <i class="fas fa-arrow-circle-right"></i>
      <% end %>
    </div>
  </div>
</div>
<div class="col-md-4 text-center">
  <div class="panel painel-default">
    <div class="panel-body">
      <p><i class="fas fa-calendar-minus"></i> 
      <%= @professor_papers_concluded%>
      Revisão Concluída</p>
    </div>
    <div class="panel-footer">
      <%= link_to professor_concluded_path, class: 'btn btn-default' do %>
        Ver Mais <i class="fas fa-arrow-circle-right"></i>
      <% end %>
    </div>
  </div>
</div>


<div class="col-md-12">
  <div class="panel panel-default">
    <div class="panel-body">
      <p><b>ARTIGO ESPERANDO COORDENADOR</b></p>
      <table id="professor-paper-without-coordinator-table">
        <thead>
          <tr>
            <th>título</th>
            <th>Professor</th>
            <th>Estado</th>
            <th>Data de submissão</th>
            <th>Informações</th>
          </tr>
        </thead>
        <tbody>
          <% if !@professor_papers.empty?%>
            <% @professor_papers.each do |paper|%>
              <tr>
                <td><%= paper.title %></td>
                <td><%= paper.professor.name %></td>
                <td><%= paper_status(paper.status) %></td>
                <td><%= paper.created_at.to_date%></td>
                <td><%= link_to 'Ver Mais', paper_show_path(paper.id), class: 'btn btn-info'%></td>
              </tr>
            <% end %>
          <% else %>
          <tr>
            <td><b>Não existe artigo submetido</b></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<div class="col-md-4">
  <%= link_to 'Submeter artigo para revisão', new_paper_path, class: 'btn btn-primary'%><br>
</div>

app/views/professors/professor_concluded_papers.html.erb
<script type="text/javascript">
  $(function(){
    document.addEventListener("turbolinks:before-cache", function() {
      dataTable.destroy();
    });
    var dataTable = $("#professor-paper-concluded-table").DataTable();
  })
</script>
<div class="row">
  <div class="col-md-12">
    <p><%= link_to "Voltar", root_path, class: 'btn btn-info'%></p>
  </div>
</div>

<div class="row">
<div class="col-md-12">
  <div class="panel panel-default">
    <div class="panel-body">
      <p><b>REVISÃO CONCLUÍDA</b></p>
      <table id="professor-paper-concluded-table">
        <thead>
          <tr>
            <th>título</th>
            <th>Professor</th>
            <th>Estado</th>
            <th>Informações</th>
            <th>Histórico</th>
          </tr>
        </thead>
        <tbody>
          <% if !@professor_papers_concluded.empty?%>
          <% @professor_papers_concluded.each do |paper|%>
          <tr>
            <td><%= paper.title %></td>
            <td><%= paper.professor.name %></td>
            <td><%= paper_status(paper.status) %></td>
            <td><%= link_to 'Ver Mais', paper_show_path(paper.id), class: 'btn btn-info'%></td>
            <td><%= link_to 'Ver Histórico', events_path(paper.id)%></td>
          </tr>
          <% end %>
          <% else %>
          <tr>
            <td><b>Não existe artigo submetido</b></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
</div>

app/views/professors/professor_pending_papers.html.erb
<script type="text/javascript">
  $(function(){
    document.addEventListener("turbolinks:before-cache", function() {
      dataTable.destroy();
    });
    var dataTable = $("#professor-paper-without-coordinator-table").DataTable();
  })
</script>

<div class="row">
  <div class="col-md-12">
    <p><%= link_to "Voltar", root_path, class: 'btn btn-info'%></p>
  </div>
</div>

<div class="col-md-12">
  <div class="panel panel-default">
    <div class="panel-body">
      <p><b>ARTIGO ESPERANDO REVISÃO</b></p>
      <table id="professor-paper-without-coordinator-table">
        <thead>
          <tr>
            <th>título</th>
            <th>Professor</th>
            <th>Estado</th>
            <th>Informações</th>
            <th>Histórico</th>
          </tr>
        </thead>
        <tbody>
          <% if !@professor_papers_pending.empty?%>
          <% @professor_papers_pending.each do |paper|%>
          <tr>
            <td><%= paper.title %></td>
            <td><%= paper.professor.name %></td>
            <td><%= paper_status(paper.status) %></td>
            <td><%= link_to 'Ver Mais', paper_show_path(paper.id), class: 'btn btn-info'%></td>
            <td><%= link_to 'Ver Histórico', events_path(paper.id)%></td>
          </tr>
          <% end %>
          <% else %>
          <tr>
            <td><b>Não existe artigo submetido</b></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>