config/routes.rb
Rails.application.routes.draw do

  
  resources :papers, except: [:show]
  get '/papers/:id/veja' => 'papers#show', as: :paper_show 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  # Way to configure Root path for some controller generated by devise

  #PDF View
  mount PdfjsViewer::Rails::Engine => "/pdfjs", as: 'pdfjs'
  
  
  
  
  #get '/pdf_render' => 'application#pdf_render', as: :pdf_render


  authenticated :coordinator do
    root 'coordinators#index', as: :authenticated_coordinator_root
    get 'coordinator/pending' => 'coordinators#coordinator_pendings_papers', as: :coordinator_pendings
    get 'coordinator/onhold' => 'coordinators#coordinator_onhold_papers', as: :coordinator_onhold
    get 'coordinator/concluded' => 'coordinators#coordinator_concluded_papers', as: :coordinator_concluded
    get 'coordinator/index' => 'coordinators#index', as: :coordinator_index
    get 'coordinator/take_paper' => 'coordinators#take_paper', as: :take_paper
    get 'coordinator/return_paper' => 'coordinators#return_paper', as: :return_paper
    patch 'coordinator/allocate' => 'coordinators#allocate_reviewer', as: 'allocate_reviewer'
    get 'coordinator/desallocate' => 'coordinators#desallocate_reviewer', as: 'desallocate_reviewer'
    patch 'coordinator/concluded' => 'coordinators#concluded?', as: :concluded
    get 'coordinator/:paper_id/veja-mais' => 'coordinators#show_paper', as: :coordinator_show_paper
    get 'historico' => 'coordinators#coordinator_events', as: :coordinator_events

     # PDF VIEW
    get 'coordinator/:paper_id/pdf_render' => 'application#pdf_render'
  end
  authenticated :professor do
    get '/papers/:id/pdf_render' => 'application#pdf_render'
    root 'professors#index', as: :authenticated_professor_root
    get 'professor/pending' => 'professors#professor_pending_papers', as: :professor_pending
    get 'professor/concluded' => 'professors#professor_concluded_papers', as: :professor_concluded
    get 'professor/:paper_id/historico' => 'professors#events', as: :events
    get 'professor/index' => 'professors#index', as: :professor_index
  end
  authenticated :reviewer do
    root 'reviewers#index', as: :authenticated_reviewer_root
    get 'reviewer/pending' => 'reviewers#reviewer_pending_papers', as: :reviewer_pending
    get 'reviewer/concluded' => 'reviewers#reviewer_concluded_papers', as: :reviewer_concluded
    get 'reviewer/index' => 'reviewers#index', as: :reviewer_index
    get 'reviewer/:paper_id/edit' => 'reviewers#reviewer_edit', as: :reviewer_edit
    patch 'reviewer/edit/save' => 'reviewers#reviewer_save', as: :reviewer_save

    #PDF VIEW
    get 'reviewer/:paper_id/pdf_render' => 'application#pdf_render' 
  end
  

  
  devise_for :professors, controllers: {
    sessions: 'professors/sessions',
    passwords: 'professors/passwords'
  }
  devise_for :coordinators, controllers: {
    sessions: 'coordinators/sessions',
    passwords: 'coordinators/passwords'
  }
  devise_for :reviewers, controllers: {
    sessions: 'reviewers/sessions',
    passwords: 'reviewers/passwords'
  }

  # Login
  get 'login' => "logins#login", as: :logins
  get 'update_login_form' => "logins#update_login_form", as: :update_login_form

  # Root definition: in the end of file
  root 'logins#login'

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SistemaRevisao</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'professor', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'professor', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar">
      <nav class="navbar-default">
        <div class="container">
          <div class="navbar-header">
            <small>Bem Vindo, <%#= current_coordinator.name %></small>
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Alterna navega&ccedil;&atilde;o</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
              <li class="dropdown active">
                  <a href="#" class="dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                      Descricao
                    <span class="caret"></span></a>
                  <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                    <li class="dropdown-header">Modulo 1</li>
                    <li><a href="">Opcao 1</a></li>
                    <li><a href="">Opcao 2</a></li>
                    <li role="separator" class="divider"></li>
                    <li class="dropdown-header">Modulo 2</li>
                    <li><a href="">Opcao 1</a></li>
                  </ul>
              </li>
              <li><a href="#" onClick="efetuarLogoff();">Sair</a></li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <% if professor_signed_in?%>
      <%= link_to 'Logout professor', destroy_professor_session_path, method: :delete%> |
      <%= link_to 'professor index', professor_index_path%>
    <% elsif coordinator_signed_in? %>
      <%= link_to 'Logout coordenador', destroy_coordinator_session_path, method: :delete%> |
      <%= link_to 'coordenador index', coordinator_index_path%>
    <% elsif reviewer_signed_in?%>
      <%= link_to 'Logout revisor', destroy_reviewer_session_path, method: :delete%> |
      <%= link_to 'revisor index', reviewer_index_path%>
    <%end%>
    <br>
    <% unless coordinator_signed_in? || professor_signed_in? || reviewer_signed_in? %>
      <%= link_to 'Login ', logins_path%> <br>
    <% end %> 

    <%= yield %>

    <%= link_to 'Início', papers_path%>
  </body>
</html>

app/views/layouts/coordinator.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SistemaRevisao</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'coordinator', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'coordinator', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
  </head>

  <body>
    <header class="navbar">
      <nav class="navbar-default">
        <div class="container">
          <div class="navbar-header">
            <a class="navbar-brand" href="/"><small>Bem Vindo, <%= current_coordinator.name %></small></a>
            
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
              <li class=""><a class="navbar-brand" href="/"><small>Página Inicial</small></a></li>
              <li><a data-confirm="Tem certeza que deseja sair?" data-method="delete" class="navbar-brand" href="/coordinators/sign_out"><small>Sair</small></a></li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <div class="container">
      <%= yield %>
    </div>
    <div class="container">
      <div class="col-md-12">
        <div class="panel panel-default">
          <div class="panel-heading">
            <p><b>LEGENDA</b></p>
          </div>
          <div class="panel-body">
            <div class="row">
              <div class="col-md-1">
                <p class="text-center"><i class="fas fa-window-close"></i></p>
              </div>
              <div class="col-md-11">
                <p>Desvincular-se do Artigo.</p>
              </div>
            </div>

            <div class="row">
              <div class="col-md-1">
                <p class="text-center"><a class="btn btn-info">Ver Mais</a></p>
              </div>
              <div class="col-md-11">
                <p>Obter e realizar ações sobre um artigo.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>

<html lang="pt-br">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <%= stylesheet_link_tag    'login', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'login', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="modal fade" id="alerta-mensagens" tabindex="-1" role="dialog">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title">Titulo da janela</h4>
          </div>
          <div class="modal-body">
            <p>mensagem</p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
            <button type="button" class="btn btn-primary">Save changes</button>
          </div>
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

    <div class="jumbotron">
      <div class="container">
        <div align="center"><img src="/images/revisao-logo-round.png"></div>
      </div>
    </div>
    <div class="container">

      <%= yield %>
    
    </div>

    <footer class="footer text-center">
      <div class="container">
        <p class="text-muted">&copy; 2018 <a href="http://www.prppg.ufc.br">Pr&oacute;-Reitoria de Pesquisa e P&oacute;s-Gradua&ccedil&atilde;o</a> &nbsp;|&nbsp;

          Assessoria de Tecnologia da Informa&ccedil;&atilde;o</p>
      </div>
    </footer>
  </body>
</html>

app/views/layouts/professor.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SistemaRevisao</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'professor', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'professor', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
  </head>

  <body>
    <header class="navbar">
      <nav class="navbar-default">
        <div class="container">
          <div class="navbar-header">
            <a class="navbar-brand" href="/"><small>Bem Vindo, <%= current_professor.name %></small></a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
              <li class=""><a class="navbar-brand" href="/"><small>Página Inicial</small></a></li>
              <li><a data-confirm="Tem certeza que deseja sair?" data-method="delete" class="navbar-brand" href="/professors/sign_out"><small>Sair</small></a></li>
              
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/layouts/reviewer.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SistemaRevisao</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'reviewer', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'reviewer', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
  </head>

  <body>
    <header class="navbar">
      <nav class="navbar-default">
        <div class="container">
          <div class="navbar-header">
            <a class="navbar-brand" href="/"><small>Bem Vindo, <%= current_reviewer.name %></small></a>
            
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
              <li class=""><a class="navbar-brand" href="/"><small>Página Inicial</small></a></li>
              <li><a data-confirm="Tem certeza que deseja sair?" data-method="delete" class="navbar-brand" href="/reviewers/sign_out"><small>Sair</small></a></li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <div class="container">
    <%= yield %>
  </div>
  <div class="container">
      <div class="col-md-12">
        <div class="panel panel-default">
          <div class="panel-heading">
            <p><b>LEGENDA</b></p>
          </div>
          <div class="panel-body">
            <div class="row">
              <div class="col-md-1">
                <p class="text-center"><a class="btn btn-info">Ver Mais</a></p>
              </div>
              <div class="col-md-11">
                <p>Obter e realizar ações sobre um artigo.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>